# Generated by Django 4.1.2 on 2022-10-27 02:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=600)),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='creation date')),
            ],
        ),
        migrations.CreateModel(
            name='Substitution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('swap_id', models.IntegerField()),
                ('pos', models.CharField(max_length=10)),
                ('tag', models.CharField(max_length=10)),
                ('base_text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.basetext')),
            ],
        ),
    ]
